# Generated by Django 4.2 on 2023-04-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(choices=[('Tanga', 'Tanga'), ('Chachetero', 'Chachetero'), ('Top Clasico', 'Top Clasico'), ('Top Deportivo', 'Top Deportivo'), ('Short', 'Short'), ('Duo Clasico', 'Duo Clasico'), ('Duo Deportivo', 'Duo Deportivo'), ('Duo Short', 'Duo Short'), ('Trio', 'Trio'), ('Boxer', 'Boxer')], max_length=50)),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
