# Generated by Django 4.2 on 2023-04-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='prenda',
            field=models.CharField(choices=[('Tanga', 'Tanga'), ('Cachetero', 'Chachetero'), ('Top Clasico', 'Top Clasico'), ('Top Deportivo', 'Top Deportivo'), ('Short', 'Short'), ('Duo Clasico', 'Duo Clasico'), ('Duo Deportivo', 'Duo Deportivo'), ('Duo Short', 'Duo Short'), ('Trio', 'Trio'), ('Boxer', 'Boxer')], max_length=50),
        ),
    ]
